PROMPT_TEMPLATES = {
    "text": {
        "blog_post": [
            "Explain the rise of diffusion-based video generation models and compare them to transformer-based approaches for creative industries.",
            "Write a beginner-friendly introduction to fine-tuning large language models using open-source frameworks like Hugging Face.",
            "Discuss the ethical challenges of generative AI in content creation, focusing on deepfakes and misinformation.",
            "Write a technical breakdown of how LoRA fine-tuning works and why it's more efficient than full model retraining.",
            "Compare WAN 2.2, OmniGen2, and Runway Gen-3—what are their strengths and weaknesses in video generation?",
            "Analyze the top penetration testing tools every ethical hacker should know in 2025.",
            "Write a guide for developers on securing Docker containers in cloud-based AI pipelines.",
            "Explain the growing risks of AI-driven phishing attacks and how companies can defend against them.",
            "Create a tutorial on setting up a home lab for practicing ethical hacking and network pen-testing.",
            "Discuss the role of AI in next-generation intrusion detection systems.",
            "Write a practical guide for solo developers turning side projects into profitable startups.",
            "Analyze the pros and cons of bootstrapping vs. VC funding for AI startups.",
            "Provide a case study of how a small team can leverage AI tools to accelerate product development.",
            "Explain how to create a minimum viable product (MVP) in just 30 days using modern frameworks.",
            "Discuss strategies for branding and marketing a startup with minimal budget.",
            "Explain the “two brains method” for managing multiple projects simultaneously.",
            "Write a blog post about how to use AI agents for time management and task prioritization.",
            "Compare different focus techniques—Pomodoro, Deep Work, and Flow—for software developers.",
            "Provide an actionable guide on balancing side hustles with a full-time job in tech.",
            "Write about the best open-source tools to automate repetitive daily tasks.",
            "Predict how WebAssembly will shape the next generation of web apps.",
            "Discuss the role of self-hosting AI models for privacy-first applications.",
            "Write a guide to building lightweight microservices with FastAPI and Docker.",
            "Explain the future of AI-powered code assistants beyond GitHub Copilot.",
            "Provide a comparison of cloud providers (AWS, GCP, Runpod, Lambda Labs) for running AI workloads.",
            "Design a modular prompt engineering workflow for consistent long-form blog generation across multiple niches.",
            "Write a step-by-step guide to building a scalable AI content pipeline using FastAPI, Celery, and Redis.",
            "Explain how to evaluate LLM outputs for factuality and bias using automated guardrails and human-in-the-loop review.",
            "Compare retrieval-augmented generation (RAG) strategies for technical blogs: local vector DB vs. hosted APIs.",
            "Create a blueprint for auto-tagging and SEO-optimizing blog posts using embeddings and keyword extraction.",
            "Write a practical guide to hardening a home lab network using VLANs, pfSense, and Zero Trust principles.",
            "Explain how to perform a secure Docker image supply chain: image signing, SBOMs, and vulnerability scanning.",
            "Analyze the most common misconfigurations found in self-hosted AI inference servers—and how to fix them.",
            "Create a beginner-friendly walkthrough for using Burp Suite to test modern single-page applications.",
            "Discuss how AI is changing red teaming and blue teaming workflows with autonomous agents and simulations.",
            "Explain a lightweight framework for validating startup ideas using landing pages, waitlists, and micro-MVPs.",
            "Write a playbook for launching a SaaS as a solo founder: pricing, onboarding, billing, and support loops.",
            "Compare common go-to-market motions for devtools startups: PLG, community-led growth, and enterprise sales.",
            "Create a founder’s guide to building with open-source first while preparing for a commercial license path.",
            "Break down how to run effective customer discovery interviews for technical products with developer users.",
            "Write a pragmatic system for task triage when juggling multiple products: ICE scoring vs. RICE vs. MoSCoW.",
            "Explain how to build a personal knowledge system using Obsidian, spaced repetition, and daily reviews.",
            "Create a weekly planning method for indie hackers that balances deep work, shipping, and marketing.",
            "Discuss using AI copilots to reduce cognitive load during context switching across multiple codebases.",
            "Write a guide to automating repetitive creator workflows: thumbnails, titles, descriptions, and clips.",
            "Analyze the shift to edge AI inference: when to use ONNX Runtime, TensorRT, or WebGPU.",
            "Create a tutorial for building a production-grade FastAPI service with JWT auth, rate limiting, and logging.",
            "Explain how to design resilient Docker Compose stacks with healthchecks, restart policies, and dependencies.",
            "Discuss the trade-offs between serverless functions and always-on GPU instances for AI workloads.",
            "Write a step-by-step migration plan from monolith to microservices for a small SaaS with minimal downtime.",
            "Create a beginner-friendly Blender tutorial to model, UV unwrap, and texture a low-poly game prop with PBR workflow.",
            "Explain how to set up a non-destructive modeling stack in Blender using modifiers for fast iteration.",
            "Write a guide to baking high-to-low poly normals and ambient occlusion for real-time assets in Unity or Unreal.",
            "Compare Eevee vs. Cycles for product visualization and when to choose each in a studio pipeline.",
            "Document a complete workflow to rig and animate a simple game character, including IK/FK switching and export.",
            "Analyze the evolution of indie horror game design: sound design, environmental storytelling, and tension pacing.",
            "Write a technical post on integrating state machines for AI enemies in Unity using ScriptableObjects.",
            "Create a performance optimization checklist for Unity mobile games: batching, lightmaps, and texture atlases.",
            "Explain how to implement save/load systems securely in games, covering encryption and anti-tamper basics.",
            "Discuss how procedural generation changes replayability and scope management for small indie teams.",
            "Write a blueprint for a content creation system that repurposes blog posts into TikTok scripts, shorts, and threads.",
            "Create a guide to data-driven TikTok A/B tests: hooks, pacing, captions, sounds, and retention curves.",
            "Explain how to build an automated B-roll and captioning pipeline using FFMPEG and whisper-based transcription.",
            "Discuss ethical and legal considerations when using AI voices and likenesses in short-form content.",
            "Provide a content calendar template for technical creators posting across TikTok, YouTube Shorts, and X.",
            "Explain how to architect a RAG system for developer documentation with chunking, re-ranking, and evals.",
            "Write a tutorial to deploy a self-hosted Ollama-based API behind Nginx with TLS, auth, and usage quotas.",
            "Compare container-native GPU scheduling options: Docker, Kubernetes with device plugins, and Runpod templates.",
            "Create a guide for building a streaming endpoint for LLMs with Server-Sent Events and backpressure handling.",
            "Discuss patterns for cost monitoring and alerting on GPU-heavy workloads with Prometheus and Grafana.",
            "Write a practical SEO guide for technical blogs: topical clustering, internal linking, and schema markup.",
            "Create a checklist for making technical tutorials reproducible: seeds, versions, hardware, and datasets.",
            "Explain how to run effective user onboarding experiments with feature tours, checklists, and empty states.",
            "Discuss pricing psychology for developer tools: freemium caps, usage-based billing, and value metrics.",
            "Provide a postmortem template for failed experiments that still produce valuable product insights.",
            "Explain a blueprint for building a privacy-first AI note-taking app with local embeddings, on-device inference, and encrypted sync.",
            "Write a technical deep dive on vector database indexing strategies (HNSW, IVF, PQ) and when each is appropriate.",
            "Create a guide to building a multi-tenant SaaS with row-level security, per-tenant rate limits, and usage metering.",
            "Discuss patterns for evaluating LLM agents: task-success metrics, tool-use accuracy, and hallucination audits.",
            "Explain how to productionize RAG with evaluation harnesses, ground-truth sets, and continuous retraining loops.",
            "Write a tutorial on provisioning GPU runners in CI to automate model evals and performance regression tests.",
            "Compare modern API gateways (Kong, Traefik, Envoy) for AI microservices, including auth, quotas, and observability.",
            "Create a playbook for incident response in AI systems: model rollbacks, feature flags, and hotfix pipelines.",
            "Explain advanced Docker networking: macvlan, IPvLAN, overlay networks, and service discovery patterns.",
            "Write a step-by-step guide to designing a developer portal with API keys, SDKs, Postman collections, and examples.",
            "Discuss BYOC (bring your own cloud) architecture for enterprise AI: security boundaries, billing, and isolation.",
            "Explain how to implement usage-based billing for AI tokens and GPU minutes with metering and aggregation.",
            "Create a practical guide to A/B/n testing prompts and system messages for long-form content generation.",
            "Write a post on creating high-signal technical case studies: problem framing, metrics, and reproducible artifacts.",
            "Discuss techniques to reduce LLM inference costs: quantization, speculative decoding, and caching strategies.",
            "Explain how to build a plugin system for an AI app using sandboxed runtimes, permissions, and manifest schemas.",
            "Create a deploy checklist for GPU workloads: pinned drivers, CUDA/cuDNN versions, container images, and tests.",
            "Write a hands-on guide to implementing background jobs for video processing pipelines with idempotency and retries.",
            "Discuss data governance for AI products: PII detection, retention policies, consent, and audit logs.",
            "Explain how to create a self-serve analytics stack using PostHog, dbt, and a lakehouse for product telemetry.",
            "Write a tutorial to build a CLI tool in Python that wraps an LLM API with streaming, retries, and structured outputs.",
            "Create a practical guide for model card documentation: capabilities, limitations, risks, datasets, and evals.",
            "Discuss the lifecycle of an AI feature from spike to GA: alpha flags, canary users, and rollout safeguards.",
            "Explain how to structure a technical blog that ranks: search intent mapping, entity coverage, and linkable assets.",
            "Write a comprehensive founder’s dashboard spec that tracks revenue, churn, activation, and R&D velocity."
        ],
    },
    "image": {
        "photorealistic": [
            "Candid street portrait of a software engineer on a rainy Tokyo night, neon reflections, 50mm lens, f/1.8, shallow depth, cinematic bokeh, wet asphalt, natural skin tones, soft rim light from signage, high detail pores, realistic raindrops.",
            "Editorial fashion shot on a rooftop at golden hour, minimalist monochrome outfit, 85mm lens, soft backlight, wind in fabric, subtle lens flare, accurate skin texture, crisp shadows, realistic city skyline depth haze.",
            "Chef plating gourmet salmon with microgreens in a stainless kitchen, overhead 35mm, diffused softbox lighting, steam visible, color-accurate food tones, shallow DOF on plate, high detail garnish, natural hands.",
            "Minimalist product shot of a matte black smartphone on concrete slab, 70mm lens, soft top-down lighting, realistic reflections, precise chamfer edges, subtle dust specks, shadow gradient, studio backdrop gray.",
            "Corporate headshot in window-lit office, 85mm, catchlights in eyes, neutral color grading, detailed hair strands, natural skin texture, soft background blur with plants and shelves, confident expression.",
            "Fitness portrait in a gritty gym, 35mm, side hard light, chalk dust in air, sweat sheen on skin, muscle definition, black rubber flooring, kettlebells and racks, realistic motion blur jump rope.",
            "Street fashion closeup of sneakers stepping through a puddle, 50mm macro feel, splash frozen midair, wet leather texture, realistic reflections, overcast lighting, gritty sidewalk details.",
            "Barber shop interior with a client mid-fade, 35mm, mixed warm practicals and cool window light, hair clippings on cape, chrome tools on counter, realistic mirror reflections, shallow DOF.",
            "Professional chef torching crème brûlée, 50mm, torch flame blue edge, sugar caramelizing, porcelain ramekin texture, controlled highlights, stainless counter reflections, shallow DOF.",
            "Skincare product flat lay on linen, 70mm top-down, soft natural daylight, realistic glass bottle reflections, water droplets, eucalyptus leaves, color-true creams, subtle shadows.",
            "Studio portrait of an elderly woman, 85mm, Rembrandt lighting, deep wrinkles detail, neutral backdrop, silver hair texture, warm skin tones, soft falloff, gentle smile.",
            "Business meeting scene with diverse team around glass table, 35mm, backlit windows, laptop reflections, pens and notes, realistic screen glow, shallow DOF on speaker.",
            "Luxury watch macro on wrist, 100mm macro, brushed steel texture, sapphire crystal reflections, skin pores, cuff fabric fibers, realistic wrist hair, soft directional light.",
            "Coffee latte art close-up in a ceramic cup, 50mm, soft morning window light, crema texture, steam wisps, wooden table grain, scattered beans, realistic foam microbubbles.",
            "Hairstyle editorial with braided updo, 85mm, high-key soft lighting, detailed hair strands, flyaways, clean background, natural skin texture, minimal makeup.",
            "Gourmet burger on slate board, 35mm, juicy patty, melted cheese stretch, sesame seed detail, tomato condensation, crisp lettuce, directional side light, realistic grease sheen.",
            "Luxury perfume bottle on mirrored surface with water ripples, 70mm, controlled highlights, crisp typography, glass refractions, soft gradient backdrop, elegant composition.",
            "Portrait of a software founder in a modern co-working space, 50mm, natural window light, laptops, plant backdrop, subtle rim light, authentic expression, realistic desk clutter.",
            "Street food vendor at dusk, 35mm, glowing stall lights, steam rising, colorful ingredients, wet cobblestones, genuine customer interaction, shallow DOF.",
            "Macro of fabric textures: wool, silk, denim, 100mm macro, directional raking light, weave detail, true-to-life color, clean composition, shallow DOF strips.",
            "High-end sneaker product on acrylic riser, 70mm, hard edge light, realistic suede/leather stitching, clean white sweep background, controlled shadows, branding sharp.",
            "Cinematic night portrait under umbrella, 85mm, city neon reflections, raindrops on fabric, soft rim light, realistic skin tones, wet hair strands, shallow DOF.",
            "Fine dining dessert plated with gold leaf, 50mm overhead, softbox diffused, true color fruit glaze, powdered sugar dusting, white porcelain plate, clean negative space.",
            "Craftsman working leather wallet, 35mm, warm workshop lamps, hands with tool marks, leather grain detail, wood bench scratches, shallow DOF on stitching.",
            "Makeup closeup: glossy lips and winged eyeliner, 100mm macro, precise highlights, skin pores, realistic specular reflections, balanced tones, clean background.",
            "Modern concrete house at sunset, 24mm, soft warm light, glass reflections, accurate perspective lines, landscaped grasses, subtle lens flare, moody sky.",
            "Minimalist Scandinavian living room, 35mm, natural window light, linen sofa texture, oak floor grain, matte ceramics, realistic shadows, balanced white balance.",
            "Cozy reading nook by window on rainy day, 35mm, water droplets on glass, soft blanket fibers, steam from mug, book pages detail, subdued tones.",
            "Luxury hotel lobby with marble floors, 24mm, high ceilings, chandelier reflections, polished surfaces, people in motion blur, warm ambient lighting.",
            "Industrial loft kitchen, 24mm, brick texture, metal shelving, matte black fixtures, diffused daylight, realistic reflections on stainless appliances.",
            "Dense mossy forest with sunbeams, 24mm, volumetric light, damp ground textures, ferns detail, soft mist, natural greens, shallow depth layering.",
            "Desert dunes at golden hour, 70mm, wind-sculpted ripples, long shadows, warm tones, crisp horizon, heat haze, minimal composition.",
            "Mountain lake at dawn, 24mm, mirror reflection, alpine pines, cool mist, pastel sky, rocks foreground detail, clean water caustics.",
            "Tropical beach cove midday, 24mm, turquoise water, coral detail, wet rocks sheen, palm shadows, realistic waves, high-contrast sunlight.",
            "Ancient stone temple at blue hour, 35mm, moody sky, torches or lanterns glow, aged stone textures, soft ground fog, realistic wear.",
            "Modern electric motorcycle in studio, 70mm, dramatic side light, matte paint, rubber tire texture, chain detail, clean gradient backdrop.",
            "Classic car parked under streetlamp at night, 50mm, chrome reflections, wet pavement glow, subtle smoke, cinematic contrast.",
            "High-speed train arriving at platform, 24mm, motion blur on train, sharp commuters, metal and glass reflections, morning light.",
            "City skyline at twilight from rooftop, 24mm, blue-orange contrast, reflective glass, traffic light trails, atmospheric depth.",
            "Private jet interior, 24mm, cream leather texture, wood veneer, soft indirect lighting, realistic screen glow, champagne glasses.",
            "Minimalist bathroom with stone sink, 24mm, soft daylight, water droplets, matte black hardware, towel fibers, subtle steam.",
            "Urban alley with wet bricks after rain, 35mm, puddle reflections, neon signage, trash bags and textures, moody contrast.",
            "Snowy cabin exterior at dusk, 35mm, warm window glow, snow accumulation details, chimney smoke, frosted branches, footsteps.",
            "Rice terraces with farmers at sunrise, 24mm, mist layers, water reflections, green gradation, authentic clothing textures.",
            "Cliffside lighthouse in stormy weather, 35mm, dramatic waves, rain streaks, wet rocks, moody sky, distant birds.",
            "Airport terminal interior, 24mm, glass and metal geometry, moving walkway blur, signage, realistic reflections and shadows.",
            "Canyon overlook at sunset, 24mm, layered rock textures, warm rim light, distant haze, small hikers for scale.",
            "Night market food street, 35mm, colorful stalls, steam and smoke, wet pavement reflections, crowds, overhead bulbs.",
            "Subway car interior at rush hour, 24mm, mixed lighting, stainless poles, realistic skin tones, ads and stickers detail.",
            "Harbor with fishing boats at dawn, 35mm, water ripples, rope textures, seagulls, soft pastel light, weathered paint.",
            "Golden retriever running on a beach, 70mm, sand kick-up, wet fur texture, natural motion blur, warm sunset light, sharp eyes.",
            "Cat lounging by window, 85mm, soft rim light on fur, whisker detail, dust motes in light beam, gentle color palette.",
            "Horse portrait in stable, 85mm, detailed mane, leather bridle texture, warm barn light, shallow background.",
            "Tropical fish in clear reef shallows, 35mm underwater look, caustics, coral detail, air bubbles, sunlight rays.",
            "Owl perched on branch at dusk, 200mm, feather detail, catchlight eyes, soft background bokeh, cool tones.",
            "Bee on sunflower macro, 100mm macro, pollen grains visible, wing detail, natural daylight, shallow DOF.",
            "Dew on spiderweb at sunrise, 100mm macro, backlit droplets, bokeh highlights, fine strands, soft background.",
            "Close-up of watch movement gears, 100mm macro, brushed metal, engraved text, oil sheen, precise highlights.",
            "Pharmaceutical pills on blue background, 70mm, blister pack reflections, embossing detail, clean clinical light.",
            "Laboratory bench with glassware, 35mm, realistic reflections, meniscus lines, condensation, soft cool lighting.",
            "Microscope closeup with specimen slide, 70mm, crisp knurled knobs, glass reflections, shallow DOF, sterile tones.",
            "Human hand holding microchip, 85mm, skin pores, chip contacts detail, soft neutral light, clean background.",
            "DNA model on lab table, 50mm, plastic texture, depth of field layering, subtle bokeh, cool color grading.",
            "Hospital room with patient and doctor, 35mm, realistic monitors, skin tones, surgical mask texture, soft overhead light.",
            "Healthy meal prep containers, 50mm top-down, vibrant vegetables, condensation, clear lids, wooden table texture.",
            "X-ray film on lightbox, 70mm, translucent glow, fingerprints, doctor’s pen pointing, realistic reflections.",
            "Medical device closeup: pulse oximeter on finger, 100mm macro, display glow, skin creases, plastic texture.",
            "Petri dishes with colonies, 70mm top-down, agar texture, condensation, color-accurate colonies, sterile setting.",
            "Clean dentist clinic interior, 24mm, equipment reflections, chair leather texture, overhead light, cool white balance.",
            "Sports nutrition powders and shaker, 50mm, dust particles, scoop detail, matte packaging, gym bench context.",
            "Herbal supplements flat lay, 70mm, amber glass bottles, leaves, paper labels, soft daylight, muted palette.",
            "Medical prosthetic limb on workbench, 50mm, carbon fiber texture, tools scattered, workshop lighting.",
            "Emergency room hallway at night, 24mm, glossy floors, motion blur staff, signage, cool fluorescent light.",
            "Doctor’s desk with stethoscope, 50mm, paper charts, pen, laptop, natural window light, clean composition.",
            "Blood pressure measurement scene, 50mm, cuff texture, realistic arm hair, monitor display, neutral lighting.",
            "Custom-built PC internals, 35mm, RGB lighting, cable management detail, metallic heat sinks, dust-free, glass panel reflections.",
            "Robotic arm assembling electronics, 50mm, conveyor belt, precise gripper detail, industrial lighting, reflective surfaces.",
            "3D printer in action, 50mm, molten filament stringing, nozzle detail, realistic reflections, workshop background.",
            "Server rack aisle, 24mm, LED status lights, cable bundles, perforated doors, cool color grading, subtle fog.",
            "Soldering PCB closeup, 100mm macro, solder bead shine, flux smoke, component labels, shallow DOF.",
            "Warehouse with autonomous forklifts, 24mm, motion blur, stacked pallets, high bay lighting, safety markings.",
            "Drone hovering over farmland, 70mm, prop blur, sensor details, golden hour, crop textures, realistic shadows.",
            "Smart home living room with IoT devices, 24mm, screen glows, reflections, tidy modern decor, natural daylight.",
            "Electric car charging at station, 35mm, cable texture, connector detail, rain droplets, overcast reflections.",
            "Student studying with tablet in library, 35mm, soft window light, book textures, screen glow, natural skin tones.",
            "Kitchen sink with running water, 50mm, splash crown frozen, stainless reflections, soap bubbles, clean composition.",
            "Laundry room with folded towels, 35mm, fabric texture, detergent bottle reflections, soft daylight, neat layout.",
            "Bicycle repair scene, 35mm, chain grease detail, tools on pegboard, directional light, realistic hands.",
            "Farmer’s market produce stall, 35mm, vibrant colors, misted vegetables, wooden crates, morning light, people blur.",
            "Public park at sunrise with joggers, 24mm, long shadows, dew on grass, soft mist, warm tones.",
            "Home office desk setup, 35mm, mechanical keyboard closeup, monitor reflections, plant, mug steam, tidy cables.",
            "Morning breakfast table, 50mm top-down, croissant flakes, jam jar reflections, coffee crema, linen texture.",
            "Rainy bus stop scene, 35mm, wet pavement, umbrella droplets, reflections, muted palette, candid expressions.",
            "Library stacks with sunbeams, 24mm, dust particles, book spine textures, quiet mood, warm light.",
            "Baker kneading dough, 50mm, flour particles airborne, hand texture, wooden bench, directional warm light.",
            "Hands typing on laptop at night, 50mm, screen glow on skin, coffee cup steam, shallow DOF, moody lighting.",
            "Child drawing with crayons, 50mm, wax texture, paper fibers, natural daylight, soft colors, candid moment.",
            "Couple cooking together, 35mm, steam from pan, vegetable textures, warm kitchen light, genuine smiles.",
            "City crosswalk at rush hour, 24mm, motion blur pedestrians, taxi reflections, wet asphalt, high contrast.",
            "Rain-soaked window from inside car, 50mm, bokeh city lights, realistic droplets trails, moody night atmosphere."
        ],
    },
    "video": {
        "cinematic_shot": [
            "Neon-drenched Tokyo alley at midnight, light rain, reflective puddles, slow dolly-in, 35mm lens, tungsten-neon mix, moody cyberpunk ambiance, shallow depth of field, steam rising from vents.",
            "Sunset aerial of Manhattan skyline, golden hour, slow parallax orbit, 85mm telephoto compression, soft haze, dramatic clouds, subtle lens flare, orchestral crescendo mood.",
            "Mountain ridge at dawn, rolling fog in valleys, tripod locked wide 24mm, time-lapse clouds, cool blue palette shifting to warm sunrise, contemplative tone.",
            "Desert highway at noon heat, shimmering mirage, low hood-mounted shot on muscle car passing by, 50mm, harsh sun, high-contrast look, gritty Americana vibe.",
            "Rainstorm over a rainforest canopy, crane down through leaves to reveal hidden waterfall, 28mm, saturated greens, mist particles, nature documentary feel.",
            "Cyberpunk market street with holograms, overhead jib shot, neon signs flicker, 35mm, rain droplets bokeh, cool magenta-teal grading, dense crowd motion blur.",
            "Abandoned industrial warehouse, shafts of light through dust, slow push-in 40mm, handheld micro-shake, metallic textures, echoing ambience, thriller tension.",
            "Snowy Nordic village blue hour, warm window lights against cold snow, static 50mm symmetrical framing, gentle snowfall, hushed atmosphere.",
            "Aerial over futuristic megacity with skybridges, sunrise backlight silhouettes, slow tilt-reveal from street to skyline, 35mm, warm glints on glass, epic scale.",
            "Coastal cliffs at golden hour, birds gliding, gimbal lateral tracking 24mm, waves crash, warm rim light on rocks, poetic travel vibe.",
            "Ancient temple in jungle overgrowth, dolly forward through vines, 32mm, diffused light, soft greens and moss textures, sense of discovery.",
            "Storm rolling into prairie, wide 18mm low-angle, wheat bending in wind, lightning flashes, dramatic cloud stack, ominous score energy.",
            "Rooftop nighttime with city bokeh, subject silhouette smoking, 85mm shallow DOF, slow rack focus from skyline to profile, noir tone.",
            "Venice canal at dawn fog, boat gliding, 35mm gentle handheld, soft pastels, subtle water ripples, romantic wistfulness.",
            "Space elevator exterior, Earth curve below, slow orbital drift, 50mm equivalent, glints of sunlight, silent majesty, sci-fi awe.",
            "Alley chase POV, sprinting steadicam 28mm, rain slick cobblestones, sodium streetlights, breathy intensity, heavy footsteps reverb.",
            "Forest path with god rays, steadicam drift 35mm, floating pollen, warm morning hues, meditative calm, high dynamic range.",
            "Lunar surface rover, low tracking 24mm, long shadows, high-contrast grayscale, crunching regolith, subtle Earth in sky.",
            "Tropical beach thunderclouds, reverse dolly from palm silhouette, 50mm, storm light gradient, salt spray particles, melancholy beauty.",
            "Gothic cathedral interior, slow crane up to stained glass, 40mm, volumetric light beams, organ-like reverb mood.",
            "Futuristic train interior, streaking lights outside windows, 35mm, neon reflections on faces, cool-teal palette, minimalist score energy.",
            "Market in Marrakech at dusk, lanterns ignite, 35mm gentle push, warm amber tones, fabric textures, lively ambience.",
            "Cliffside monastery, drone reveal from behind rock spire, 24mm, birds scatter, golden edge light, sacred tranquility.",
            "Underwater coral reef, slow gliding 18mm, shafts of light from surface, saturated tropical colors, fish schools swirl, serene silence.",
            "High-altitude snowy peak summit, 50mm telephoto compression of ridgelines, icy wind particles, crisp blue-white palette, triumphant stillness.",
            "Close-up of a pianist’s hands under warm lamp, 85mm macro feel, shallow DOF, slow lateral slide, dust motes floating, intimate tenderness.",
            "Boxer shadowboxing in a dim gym, 35mm handheld, sweat droplets, flickering fluorescents, gritty contrast, rhythmic breathing.",
            "Hacker at midnight desk, monitors glow blue, 50mm static profile, light only from screens, rain on window, tense minimalism.",
            "Couple on subway platform at 2am, 35mm dolly, train wind rush, amber overhead lights, neon ads flicker, bittersweet goodbye mood.",
            "Chef slicing herbs in sunlit kitchen, 50mm overhead insert, steam rising from pot, natural window light, warm color grade, cozy authenticity.",
            "Samurai in bamboo forest, slow push-in 40mm, leaves fall, soft overcast light, minimal movement, stoic resolve.",
            "Firefighter emerges from smoke, 85mm, ash particles, high-contrast backlight, slow-motion embers, heroic gravitas.",
            "Ballet rehearsal, 35mm gimbal orbit around pirouette, floor reflections, soft sepia tone, metronomic breath, disciplined grace.",
            "Street dancer under overpass, 24mm low angle, graffiti walls, skipping boombox audio vibe, kinetic urban energy.",
            "Astronaut helmet reflection of Earth, 85mm close-up, breathing fogs visor, subtle internal HUD, anxious anticipation.",
            "Detective in diner booth at night, 50mm, neon sign flicker across face, coffee steam, rain-streaked window, noir melancholy.",
            "Desert drifter walking toward heat haze horizon, 35mm tracking, dust cloud trailing, sun-blasted color, existential quiet.",
            "Old watchmaker at bench, 85mm macro parts, tungsten lamp glow, antique tools, soft classical undertone, patient craftsmanship.",
            "Protest crowd at golden hour, 24mm wide, flags wave, sunlight flares, faces determined, hopeful urgency.",
            "Parkour leap rooftop to rooftop, 18mm POV, wind rush, brief weightless beat, hard landing, visceral adrenaline.",
            "Solo coder at sunrise rooftop, laptop glow fades as sun rises, 35mm, warm pink sky, quiet ambition.",
            "Librarian in cathedral-like archive, 50mm dolly down aisle, dust beams, leather bindings, reverent hush.",
            "Surfer paddling into massive wave, 24mm water-level tracking, droplets sparkling, deep teal, courageous calm before drop.",
            "Street vendor grilling skewers, 35mm close insert of sizzling fat, smoke curls in sunset, mouthwatering warmth.",
            "Veteran gazing at folded flag, 85mm close-up, soft backlight, quiet dignity, tear glints, solemn respect.",
            "Gamer in RGB-lit room, 28mm push through monitors, reflections in glasses, tense competitive focus, cyber ambiance.",
            "Mountain biker singletrack descent, chest-mounted 18mm, sun strobing through trees, dirt kicks up, exhilarating flow.",
            "Solo violinist in empty theater, 50mm center-frame, spotlit stage, velvet seats recede, poignant resonance.",
            "Night driver on rainy freeway, 35mm through windshield, taillight bokeh, wipers rhythm, meditative motion.",
            "Old couple holding hands on seaside promenade at dusk, 85mm, soft pastel sky, gentle breeze, enduring love.",
            "Medieval castle siege at dawn fog, 35mm crane reveal of battlements, torches flicker, banners whip, grim determination.",
            "Dragon silhouette over mountain pass, 50mm tele, sun behind wings, flock of birds scatters, mythic awe.",
            "Elven forest city glowing at twilight, 24mm slow drift, bioluminescent flora, crystalline spires, ethereal serenity.",
            "Wizard’s workshop, 50mm close inserts: glowing runes, bubbling vials, parchment maps, warm candlelight, arcane curiosity.",
            "Desert nomad caravan under star field, 24mm, lantern light pools, Milky Way vivid, contemplative silence.",
            "Futuristic hangar with mechs, 35mm dolly along maintenance crew, sparks shower, cold industrial light, grand scale.",
            "Cybernetic street courier weaving traffic, 28mm helmet POV, neon reflections, Heads-Up interface, relentless pace.",
            "Space station garden dome, 35mm, soft sun through glass, plants sway low gravity, tranquil synthesis of tech and nature.",
            "AI courtroom, 50mm symmetrical composition, holographic evidence floats, cool cyan light, clinical authority.",
            "Post-apocalyptic highway overgrown with vines, 24mm gimbal, nature reclaiming cars, birdsong over silence, haunting beauty.",
            "Haunted Victorian manor corridor, 35mm creeping dolly, peeling wallpaper, flickering candelabra, breath mist, dread.",
            "Foggy graveyard at midnight, 50mm, distant church bell, ravens, moonlight shafts through trees, chilling stillness.",
            "Abandoned hospital operating room, 28mm handheld tremor, swinging surgical lamp, rusted tools, escalating anxiety.",
            "Witch’s cottage in storm, 35mm exterior, lightning silhouette, windows glow amber, rain lashes, folk horror mood.",
            "1920s speakeasy, 50mm smoky jazz ambiance, glittering dresses, warm tungsten, clandestine glamour.",
            "WWII airfield dawn, 85mm tele of pilots preflight, breath clouds in cold air, propwash dust, solemn resolve.",
            "Renaissance painter’s studio, 50mm, north light window, oils and pigments, apprentice grinding color, contemplative craft.",
            "Ancient Roman forum bustling, 24mm wide, market chatter, marble gleam, sunlit columns, historical vibrancy.",
            "Samurai duel in snowfall, 85mm tight, breath plumes, whispering wind, poised stillness before strike.",
            "Noir 1940s city street, 35mm rain, Venetian blind shadows, fedora silhouette, cigarette ember, fatalistic mood.",
            "Alien desert with triple suns, 24mm heat haze, crystal formations, strange fauna silhouettes, cosmic wonder.",
            "Starship bridge at red alert, 35mm push-in on captain, alarms pulse, cool-warm contrast, decisive command.",
            "Undersea research facility corridor, 28mm, water pressure creaks, bioluminescent creatures outside, claustrophobic tension.",
            "Time portal opens in modern alley, 35mm, swirling particles, color aberrations, onlookers stunned, uncanny rupture.",
            "Steampunk airship deck at sunrise, 50mm, brass and leather details, steam valves hiss, adventurous optimism.",
            "Santorini cliff village at sunset, 35mm, warm domes glow, sea shimmers, gentle breeze, romantic reverie.",
            "Kyoto shrine torii tunnel, 24mm steady forward, red gates repeating, soft steps, meditative rhythm.",
            "Sahara dune ridge at golden hour, 50mm tele compression, wind ripples sand, vast minimalism, quiet grandeur.",
            "Iceland waterfall in overcast, 24mm frontal symmetry, mist veil, mossy rocks, fresh cool palette, cleansing force.",
            "Rio Carnival street at night, 35mm dancing crowd, confetti and glitter, saturated colors, exuberant joy.",
            "Soccer stadium penalty shootout, 85mm on striker’s face, crowd bokeh, breath holds, explosive release.",
            "Free solo climber on granite face, 50mm side tracking from drone, chalk dust, raw exposure, nerve-wracking awe.",
            "Marathon finish line, 35mm low run-by, sweat and smiles, confetti burst, triumphant fatigue.",
            "Formula car pit stop, 85mm fast inserts: tire gun sparks, crew choreography, high-octane urgency.",
            "Street skateboarder stair set at twilight, 24mm fisheye feel, repeated tries, final land, communal stoke.",
            "Classic Porsche on coastal road, 50mm chase car shot, golden hour reflections, engine note vibe, timeless elegance.",
            "Off-road rally through mud, 28mm side spray, windshield splatter, roaring aggression, visceral power.",
            "Night city motorcycle ride, 35mm handlebar mount, neon streaks, visor reflections, adrenaline solitude.",
            "Food close-up: ramen bowl steam, 85mm macro, glistening broth, chopsticks lift noodles, cozy warmth.",
            "Street food night market, 35mm gimbal glide, sizzling grills, bright signage, bustling sensory overload.",
            "Fine dining plating, 85mm tight macro on tweezers placing microgreens, glossy sauce, pristine whites, refined artistry.",
            "Espresso pull in café, 85mm macro, crema blooming, warm wood textures, morning calm.",
            "Pastry shop morning trays, 50mm, golden croissants, powdered sugar dustings in air, inviting glow.",
            "Abstract macro: oil on water bokeh, 100mm macro, rainbow interference, slow pan, hypnotic calm.",
            "Ink diffusing in clear tank, 85mm macro, silky tendrils swirl, high-contrast color, meditative drift.",
            "Ferrofluid reacting to magnet, macro spikes forming, glossy black, sci-fi texture fascination.",
            "Vinyl record spinning, 85mm macro on stylus groove, warm tungsten, soft dust motes, nostalgic vibe.",
            "Light through prism on desk, 50mm, spectral rainbow across paper textures, quiet afternoon.",
            "Candle flame in extreme close-up, 100mm macro, wavering convection currents, dark backdrop, intimate stillness.",
            "Rain droplet races down window at night, 85mm macro, city bokeh trails behind, reflective melancholy."
        ],
    },
}